# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr9= np.arange(10).reshape(2,5)
arr9[:5,:]
arr9

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
ar1=np.arange(10).reshape(2,5)
ar2=np.arange(10,20).reshape(2,5)
ar2[:]=1
np.vstack((ar1,ar2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
ar6=np.array([0,1,2,3,4,1,1,1,1,1])
ar7 = np.array([5,6,7,8,9,1,1,1,1,1])
np.vstack((ar6,ar7))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
import numpy as np
ar10 = np.arange(10)
ar10.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr11= np.array(np.arange(15)).reshape(5,3)
np.ravel(arr11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr111 =np.array(np.arange(15)).reshape(5,3)
arr111

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr121= np.arange(25).reshape(5,5)
arr121
np.sqrt(arr121)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr123 = np.arange(30).reshape(5,6)
np.mean(arr123)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
arr124 = np.arange(30).reshape(5,6)
np.std(arr124)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
arr125 = np.arange(30).reshape(5,6)
np.median(arr125)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
arr126= np.arange(30).reshape(5,6)
np.transpose(arr126)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr129 = np.arange(16).reshape(4,4)
np.sum(arr129)

120

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
from numpy.linalg import det
arr130 = np.arange(16).reshape(4,4)
np.linalg.det(arr130)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

## Question:15

### How to find if a given array has any null values?